### ISSUE TITLE
Enable CORS for API

### ISSUE THREAD

**Issue by equisoide** [celerik/best-web-firms-bamburgh#17]
**Is your feature request related to a problem? Please describe.**
I want the Laravel API to allow Cross Domain Requests from any origin

**Describe the solution you'd like**
 - Allowed methods: All
 - Allowed origins: All
 - Allowed VERBS: all

**Comment by jorius** [comment]
This is already built in and done, it's working for all the API routes.

You can check the following files to ensure or improve the CORS behavior in Laravel:

backend/config/cors.php
backend/app/Http/Kernel.php
